# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yeongjun Jang
title: Ph.D. student at Seoul National University
email: jangyj0512@snu.ac.kr / jangyj@cdsl.kr

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  yj-jang-98
orcid_username: 0009-0007-0784-0212


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a Ph.D. Student in the [Control and Dynamic Systems Lab](https://post.cdsl.kr/) at Electrical and Computer Engineering, [Seoul National University](https://www.snu.ac.kr/index.html),
 under the supervision of Professor [Hyungbo Shim](https://hshim.wordpress.com).

 My reserach interests include encrypted control systems and learning-based control with guarantee.

 **Education**

 * (2017-2022) B.S. Electrical and Computer Engineering, Seoul National University, South Korea
     * *Fulfilled 21 months of mandatory military duting in South Korea from Aug 2018 - Mar 2020*
 * (2022-now) Combined M.S./Ph.D. student Electrical and Computer Engineering, Seoul National University, South Korea


content:    
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Path generating inverse Gaussian process regression for data-driven ultimate boundedness control of nonlinear systems
        link: https://ieeexplore.ieee.org/abstract/document/10535392
        title: Ring-LWE based encrypted controller with unlimited number of recursive multiplications and effect of error growth
        link: https://arxiv.org/abs/2406.14372
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
