# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Yeongjun Jang
email: jangyj0512@snu.ac.kr / jangyj@cdsl.kr

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  yj-jang-98
orcid_username: 0009-0007-0784-0212


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a Ph.D. Student in the [Control and Dynamic Systems Lab](https://post.cdsl.kr/) at Electrical and Computer Engineering, [Seoul National University](https://www.snu.ac.kr/index.html),
 under the supervision of Professor [Hyungbo Shim](https://hshim.wordpress.com).

 My reserach interests include encrypted control systems and learning-based control with guarantee.

 **Education**

 * (2017-2022) B.S. Electrical and Computer Engineering, Seoul National University, South Korea
     * *Fulfilled 21 months of mandatory military duty in South Korea from Aug 2018 - Mar 2020*
 * (2022-now) Combined M.S./Ph.D. student Electrical and Computer Engineering, Seoul National University, South Korea


content:    
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | 
         * "Path generating inverse Gaussian process regression for data-driven ultimate boundedness control of nonlinear systems"  
           <u>Y. Jang</u>, H. Chang, H. Park, and H. Shim  
           (LCSS 2024)
         * "Ring-LWE based encrypted controller with unlimited number of recursive multiplications and effect of error growth"  
           <u>Y. Jang</u>, J. Lee, S. Min, H. Kwak, J. Kim, and S. Song  
           (TCNS 2024 under revision)
         * "Weighted Gaussian process regression: boosting the performance of Gaussian process regression using multiple hyperparameters"  
            H. Park, H. Chang, <u>Y. Jang</u>, and H. Shim  
            (ACC 2024 under review)
         * "Learning with errors based dynamic encryption that discloses residue signal for anomaly detection"  
           <u>Y. Jang</u>, J. Lee, J. Kim, and H. Shim  
           (arXiv 2024)
  
  - title: Talks # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | 
         * Invited speaker, 2024 Group of Global Excellence (GoGE) workshop, Seoul National University, South Korea, 2024
         
        
# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
